# Generated by Django 5.0.6 on 2024-06-27 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0002_rename_name_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_file_id', models.CharField(blank=True, max_length=30, null=True)),
                ('files_id', models.CharField(blank=True, max_length=30, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='uploads/chat_files')),
            ],
        ),
        migrations.CreateModel(
            name='chat_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_msg_id', models.CharField(blank=True, max_length=30, null=True)),
                ('chat_box_id', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('chat_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contain_txt', models.BooleanField(default=False)),
                ('chat', models.TextField()),
                ('contain_file', models.BooleanField(default=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to='uploads/chat_files')),
                ('contain_files', models.BooleanField(default=False)),
                ('files_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
