# Generated by Django 5.0.6 on 2024-06-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0003_chat_file_chat_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_file',
            name='file_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chat_msg',
            name='file_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
