# Generated by Django 5.0.6 on 2024-06-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0004_chat_file_file_type_chat_msg_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_box_id', models.CharField(blank=True, max_length=30, null=True)),
                ('users', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/chats_img')),
            ],
        ),
    ]
