# Generated by Django 5.0.6 on 2024-06-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0005_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
