# Generated by Django 5.0.6 on 2024-06-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0006_chats_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='grp',
            field=models.BooleanField(default=False),
        ),
    ]
