# Generated by Django 5.0.6 on 2024-06-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0008_remove_chats_users_chats_chats_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='last_msg',
            field=models.TextField(blank=True),
        ),
    ]
