# Generated by Django 5.0.6 on 2024-06-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0009_chats_last_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='last_msg_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
