# Generated by Django 5.0.6 on 2024-06-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0010_chats_last_msg_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
