# Generated by Django 5.0.6 on 2024-06-29 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0011_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_file',
            name='file_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
