# Generated by Django 5.0.6 on 2024-06-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0012_chat_file_file_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_file',
            name='chat_box_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
