# Generated by Django 5.0.6 on 2024-06-29 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0013_chat_file_chat_box_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chats',
            new_name='Chats_BOX',
        ),
    ]
