# Generated by Django 5.0.6 on 2024-06-29 23:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0014_rename_chats_chats_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats_box',
            name='box_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
