# Generated by Django 5.0.6 on 2024-06-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0015_chats_box_box_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_msg',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chat_msg',
            name='file_type',
        ),
    ]
