# Generated by Django 5.0.6 on 2024-07-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0016_remove_chat_msg_file_remove_chat_msg_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_file',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
