# Generated by Django 5.0.6 on 2024-07-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0018_rename_files_id_chat_msg_chat_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_msg',
            old_name='chat_file_id',
            new_name='files_id',
        ),
    ]
