# Generated by Django 5.0.6 on 2024-07-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveChat_app', '0019_rename_chat_file_id_chat_msg_files_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_msg',
            name='chat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
